"""Build self-hosted, on-demand WOFF2 subsets from the licensed source fonts.

Usage: python scripts/build-editorial-fonts.py /path/to/source-font-directory
Requires fonttools[woff] and brotli. Sources and licenses are documented in public/fonts/README.md.
"""
import argparse
import json
from pathlib import Path
from fontTools import subset
from fontTools.ttLib import TTFont

parser = argparse.ArgumentParser()
parser.add_argument('source', type=Path)
args = parser.parse_args()
root = Path(__file__).resolve().parent.parent
out = root / 'public/fonts'
out.mkdir(exist_ok=True)
source = args.source / 'SourceHanSerifSC-Regular.otf'
font = TTFont(source)
codepoints = set(font.getBestCmap())
content = json.loads((root / 'content/site-content.json').read_text())
core_text = '让作品先说话近期展览喜马拉雅艺术部分藏品赏析文章与动态竹瑾居关于联系我们全部往电子图录浏览阅读查看收藏序研究参考资料重点作品图录版面'
slugs = {'artwork-1790510831618', 'artwork-1790510327321', 'artwork-1790513079613', 'artwork-1790514960631', 'why-exhibitions-matter', 'article-1773838559083', 'article-1773826628311'}
for records in content.values():
    for record in records:
        if record.get('slug') in slugs:
            core_text += record['title']['zh']
core = (set(map(ord, core_text)) | set(range(32, 256)) | set(range(0x3000, 0x3040))) & codepoints
# Non-overlapping unicode ranges allow future CMS titles to request only needed blocks.
groups = [('core', core)]
remaining = codepoints - core
for block in sorted({cp // 256 for cp in remaining}):
    groups.append((f'{block:04x}', {cp for cp in remaining if cp // 256 == block}))

def ranges(points):
    runs = []
    for cp in sorted(points):
        if runs and cp == runs[-1][1] + 1:
            runs[-1][1] = cp
        else:
            runs.append([cp, cp])
    return ','.join(f'U+{lo:X}' if lo == hi else f'U+{lo:X}-{hi:X}' for lo, hi in runs)

css = ['/* Generated by scripts/build-editorial-fonts.py; glyph ranges are disjoint. */']
for label, points in groups:
    font = TTFont(source, recalcTimestamp=False)
    options = subset.Options()
    options.flavor = 'woff2'
    options.recalc_timestamp = False
    sub = subset.Subsetter(options=options)
    sub.populate(unicodes=points)
    sub.subset(font)
    for name in font['name'].names:
        if name.nameID in (1, 3, 4, 6, 16, 17):
            value = 'Regular' if name.nameID == 17 else 'ZhujinjuSong-Regular'
            name.string = value.encode(name.getEncoding())
    if 'CFF ' in font:
        cff = font['CFF '].cff
        cff.fontNames = ['ZhujinjuSong-Regular']
        cff.topDictIndex[0].FullName = 'Zhujinju Song Regular'
        cff.topDictIndex[0].FamilyName = 'Zhujinju Song'
    font.flavor = 'woff2'
    filename = f'zhujinju-song-{label}.woff2'
    font.save(out / filename)
    css.append('@font-face {\n  font-family: "Zhujinju Song";\n  font-style: normal;\n  font-weight: 400;\n  font-display: swap;\n  src: url("/fonts/' + filename + '") format("woff2");\n  unicode-range: ' + ranges(points) + ';\n}')
css.append('@font-face { font-family: "Source Serif 4"; font-style: normal; font-weight: 400; font-display: swap; src: url("/fonts/SourceSerif4-Regular.woff2") format("woff2"); }')
(root / 'app/(site)/editorial-fonts.css').write_text('\n'.join(css) + '\n')
(out / 'SourceSerif4-Regular.woff2').write_bytes((args.source / 'SourceSerif4-Regular.woff2').read_bytes())
for name in ('LICENSE-han.txt', 'LICENSE-source-serif.md'):
    (out / name).write_bytes((args.source / name).read_bytes())
print(f'{len(groups)} subsets; core {(out / "zhujinju-song-core.woff2").stat().st_size:,} bytes')
